name: Mirror @ Murcia Organization

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-18.04
    steps:
      - id: mirroring
        run: | 
          git clone --bare https://github.com/weso/hercules-ontology.git
          cd old-repository.git
          git push --mirror https://github.com/HerculesCRUE/ib-hercules-sync.git
          
